feat: admin ui - display information on agent when refName conflict
otto8-ai/otto8 pull request #593
Opened 2024-11-14 21:14 UTC by ryanhopperlowe

![image](https://github.com/user-attachments/assets/952ccac6-e1d3-4d19-a78e-29ce92ea020f)

2024-11-14 21:20 UTC, ryanhopperlowe commented on apiclient/types/assitant.go
I wrote some Go! (please review)

2024-11-14 22:08 UTC, StrongMonkey approved these changes

2024-11-15 01:12 UTC, thedadams requested changes
I believe you'll also need to run `go generate` for these changes.

2024-11-15 01:12 UTC, thedadams commented on apiclient/types/assitant.go
> +	EntityId    string     `json:"entityId"`
This is the Go standard.
```suggestion
	EntityID    string     `json:"entityID"`
```

2024-11-15 14:41 UTC, thedadams approved these changes

2024-11-15 14:42 UTC, merged