Feat: Add file tree, add include and exclude prefix for auto ingestion
otto8-ai/otto8 pull request #639
Opened 2024-11-20 08:23 UTC by StrongMonkey

2024-11-20 18:43 UTC, ryanhopperlowe commented on ui/admin/app/components/knowledge/FileTree.tsx
> +                                        className="justify-start items-center group ml-2 hidden group-hover:block"
```suggestion
                                        className="justify-start items-center group ml-2 invisible group-hover:visible"
```

2024-11-20 18:45 UTC, ryanhopperlowe commented on ui/admin/app/components/knowledge/FileTree.tsx
> +                    <div className="flex flex-row p-2 hover:bg-accent hover:text-accent-foreground justify-between hover:cursor-pointer group">
can you remove `hover:cursor-pointer`? clicking the div doesn't actually do anything

2024-11-20 18:56 UTC, njhale requested changes

2024-11-20 18:56 UTC, njhale commented on pkg/controller/handlers/knowledgefile/knowledgefile.go
> +}
```suggestion
func hasAnyPrefix(filePath string,  prefixes []string) bool {
	for _, prefix := range prefixes {
		if strings.HasPrefix(filePath, prefix) {
			return true
		}
	}

	return false
}
```

2024-11-20 18:56 UTC, njhale commented on pkg/controller/handlers/knowledgefile/knowledgefile.go
> +	}
```suggestion
	if file.Spec.Approved == nil {
	    var approved *bool
	    
	    switch {
	    case source.Spec.Manifest.AutoApprove != nil && *source.Spec.Manifest.AutoApprove:
	        approved = typed.Pointer(true)
	    case matchExclude:
	        approved = typed.Pointer(false)
	    case matchInclude:
	        approved = typed.Pointer(true)
	    }
	    
		if approved != nil {
		    file.Spec.Approved = approved
		    if err := req.Client.Update(req.Ctx, file); err != nil {
		        return err
		    }
		}
	}
```

2024-11-20 19:25 UTC, StrongMonkey commented on ui/admin/app/components/knowledge/FileTree.tsx
> +                    <div className="flex flex-row p-2 hover:bg-accent hover:text-accent-foreground justify-between hover:cursor-pointer group">
Actually it will open and close the folder tree that's why I added this.

2024-11-20 22:34 UTC, ryanhopperlowe commented on ui/admin/app/components/knowledge/FileTree.tsx
> +                    <div className="flex flex-row p-2 hover:bg-accent hover:text-accent-foreground justify-between hover:cursor-pointer group">
I see, can you remove it when the row has no children then? I'm still seeing it for leaf nodes

2024-11-20 22:37 UTC, StrongMonkey commented on ui/admin/app/components/knowledge/FileTree.tsx
> +                    <div className="flex flex-row p-2 hover:bg-accent hover:text-accent-foreground justify-between hover:cursor-pointer group">
Oh sure 👍

2024-11-21 01:32 UTC, njhale requested changes

2024-11-21 01:32 UTC, njhale commented on pkg/controller/handlers/knowledgefile/knowledgefile.go
> +		}
The code from before you addressed my comment didn't perform an update if the value of `file.Spec.Approved` was still `nil` after checking all the approve/deny conditions; in other words, it didn't update when "no decision" about approval was reached.

This updated code __always__ performs an update, even when there's no change to `file.Spec.Approved`.

Was this change in behavior intentional?



I assumed that we _didn

2024-11-21 02:06 UTC, njhale approved these changes

2024-11-21 11:39 UTC, thedadams requested changes

2024-11-21 11:39 UTC, thedadams commented on apiclient/types/knowledgesource.go
> +	FilePathPrefixExclude   []string             `json:"filePathPrefixExclude,omitempty"`
Do we need this both here and `KnowledgeSourceManifest`? Seems like just in `KnowledgeSourceManifest` is enough.

2024-11-21 11:39 UTC, thedadams commented on pkg/api/handlers/knowledgesource.go
> +		FilePathPrefixInclude:   knowledgeSource.Spec.Manifest.FilePathPrefixInclude,
Can be removed if we use the fields from `KnowledgeSourceManifest`.

2024-11-21 11:39 UTC, thedadams commented on pkg/controller/handlers/knowledgefile/knowledgefile.go
> +		}
nit: only do the processing that's necessary.
```suggestion
		switch {
		case source.Spec.Manifest.AutoApprove != nil && *source.Spec.Manifest.AutoApprove:
			file.Spec.Approved = typed.Pointer(true)
		case isFileMatchPrefixPattern(file.Spec.FileName, source.Spec.Manifest.FilePathPrefixInclude):
			file.Spec.Approved = typed.Pointer(false)
		case isFileMatchPrefixPattern(file.Spec.FileName, source.Spec.Manifest.FilePathPrefixInclude):
			file.Spec.Approved = typed.Pointer(true)
		}
```

2024-11-21 15:45 UTC, ryanhopperlowe approved these changes

2024-11-21 15:46 UTC, ryanhopperlowe commented
<img width="443" alt="Screenshot 2024-11-21 at 9 34 30 AM" src="https://github.com/user-attachments/assets/65f9d0ee-2dcf-4d2e-a18f-1557ee323fd0">

Noticing that the add button is getting cutoff when the file name is too long. I think we need to truncate the text and add a tooltip to it

2024-11-21 15:56 UTC, ryanhopperlowe requested changes
discovered above issue

2024-11-21 16:47 UTC, StrongMonkey commented on pkg/api/handlers/knowledgesource.go
> +		FilePathPrefixInclude:   knowledgeSource.Spec.Manifest.FilePathPrefixInclude,
yeah, right. I will drop that

2024-11-21 18:05 UTC, ryanhopperlowe commented
> @ryanhopperlowe good catch, should be fixed 🙏 <img alt="image" width="947" src="https://private-user-images.githubusercontent.com/9203378/388610817-5246e494-efc6-4577-a406-796d9d58153b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTI2MDQsIm5iZiI6MTczMjIxMjMwNCwicGF0aCI6Ii85MjAzMzc4LzM4ODYxMDgxNy01MjQ2ZTQ5NC1lZmM2LTQ1NzctYTQwNi03OTZkOWQ1ODE1M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMTgwNTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2IwNTc1M2M4MGIwMjMxYzMwYjUwMDc0MTIzMWQyN2U3MThiMTQzM2UyODdiYjgyZDgzYjQzYWQ0YTk0NjEzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FleXa7Rx_DM4BFFFO9DGm1HBFlMbg7X1FAUK6dYKj8Q">

Beautiful 🙌

2024-11-21 18:05 UTC, ryanhopperlowe approved these changes

2024-11-22 09:31 UTC, iwilltry42 approved these changes

2024-11-22 20:10 UTC, thedadams approved these changes

2024-11-22 21:20 UTC, merged